apps/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('products/', views.StoreItemsView.as_view(), name='products_list_page'),
    path('products/add/', views.ProductCreateView.as_view(), name='create_product_page'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='update_product'),
]

avivi_start/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from crud_transaction.views import (
    UsersViewSet,
    BalancesViewSet,
    TransactionsViewSet
)

router = routers.SimpleRouter()
router.register(r'user', UsersViewSet)
router.register(r'balance', BalancesViewSet)
router.register(r'transaction', TransactionsViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


from .views import main_page, forbidden

from apps.crud_transaction.urls import router as crud_transaction_router
from apps.user import urls as user_urls
from apps.tg_bot import urls as tg_bots_urls
from apps.store import urls as store_urls


urlpatterns = [
    path('', main_page, name='main_page'),

    path('admin/', admin.site.urls),

    path('', include(crud_transaction_router.urls)),
    path('', include(user_urls)),
    path('', include(tg_bots_urls)),
    path('', include(store_urls)),

    path('forbidden/', forbidden, name='forbidden'),

    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/store/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    stock_quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/store/forms.py
from django import forms
from .models import Product


class StoreProductForm(forms.ModelForm):
    class Meta():
        model = Product
        fields = ('name', 'description', 'price', 'image', 'category')

apps/store/views.py
import os

from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views import View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404

from .models import Product
from .forms import StoreProductForm


class StoreItemsView(View):
    template_products_list = 'store.html'
    products_per_page = 5

    def get(self, request):
        products_list = Product.objects.all().order_by('created_at')
        paginator = Paginator(products_list, self.products_per_page)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, self.template_products_list, {'store_product_list': page_obj})


class ProductCreateView(View):
    def get(self, request):
        return render(request, 'create_store_item.html', {})

    def post(self, request):
        form = StoreProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('products_list_page'))

        return render(request, 'create_store_item.html', {'form': form})


class ProductDeleteView(View):
    def delete(self, request, *args, **kwargs):
        product_id = kwargs.get('pk')
        product = get_object_or_404(Product, id=product_id)
        if product.image:
            if os.path.isfile(product.image.path):
                os.remove(product.image.path)
        product.delete()

        return JsonResponse({}, status=204)


class ProductUpdateView(View):
    template_product_update = 'update_store_item.html'

    def get(self, request, *args, **kwargs):
        product_id = kwargs.get('pk')
        product = get_object_or_404(Product, id=product_id)
        form = StoreProductForm(instance=product)
        return render(request, self.template_product_update, {'form': form, 'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)

        if product.image:
            if os.path.isfile(product.image.path):
                os.remove(product.image.path)

        form = StoreProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('products_list_page'))

        return render(request, self.template_product_update, {'form': form})

templates/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Tg main{% endblock %}</title>
        <link rel="apple-touch-icon" href="{% static 'images/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>

    <body class="d-flex flex-column h-100">
        <header class="p-3 bg-dark text-white">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="{% url 'main_page' %}" class="nav-link px-2 text-white">Home</a></li>
                    {% if request.user.is_superuser %}
                  <li><a href="{% url 'tg_users_list' %}" class="nav-link px-2 text-white">Users</a></li>
                  <li><a href="{% url 'tg_bot_list' %}" class="nav-link px-2 text-white">Bots</a></li>
                    {% endif %}
                  <li><a href="{% url 'products_list_page' %}" class="nav-link px-2 text-white">Store</a></li>
                </ul>

              </div>
            </div>
        </header>

        <main class="flex-shrink-0">
          <div class="container">
              {% block h1 %}<h1 style="text-align: center; color:#dc3545; margin:50px;">Welcome to our service!</h1>{% endblock %}
              {% block users_list %} {%endblock%}
              {% block add_users %} {%endblock%}
              {% block bot_list %} {% endblock %}
              {% block store %} {% endblock %}
              {% block create-store-item %} {% endblock %}
              {% block forbidden %} {% endblock %}
          </div>
        </main>

        <footer class="footer mt-auto py-3 bg-body-tertiary"  style="background-color:#212529; color:#ffffff;">
          <div class="container">
            <span class="text-body-secondary">Footer content here.</span>
          </div>
        </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="module" src="{% static 'js/main.js' %}" defer></script>
    </body>
</html>

templates/bot_management.html
{% extends 'base.html' %}
{% block title %}Tg bots{% endblock %}
{% block h1 %}<h1 style="text-align:center; margin:20px;">Telegram bots</h1>{% endblock %}

{% block bot_list %}
<div class="container mt-4">
    <h2>Create new bot</h2>
    <form action="{% url 'tg_bot_list' %}" method="POST">
    {% csrf_token %}
        <div class="form-group" style="margin-top: 15px;">
            <label for="id_bot_name_zero">Bot Name</label>
            <input type="text" class="form-control" id="id_bot_name_zero" name="bot_name">
        </div>

        <div class="form-group" style="margin-top: 15px;">
            <label for="id_api_key_zero">API Key</label>
            <input type="text" class="form-control" id="id_api_key_zero" name="api_key">
        </div>

        <div class="form-group" style="margin-top: 15px;">
            <label for="id_webhook_url_zero">Webhook URL</label>
            <input type="url" class="form-control" id="id_webhook_url_zero" name="webhook_url">
        </div>

        <button type="submit" class="btn btn-primary" style="margin-top:20px;">Create</button>
    {{form.errors}}
    </form>
</div>

<h2>Bot list</h2>
{% if tg_bots %}
<div class="accordion" id="accordionExample" style="margin-bottom:50px;">
    {% for tg_bot in tg_bots%}
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading{{ tg_bot.pk }}">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ tg_bot.pk }}" aria-expanded="true" aria-controls="collapse{{ tg_bot.pk }}">
            {{tg_bot.bot_name}}
          </button>
        </h2>
        <div id="collapse{{ tg_bot.pk }}" class="accordion-collapse collapse" aria-labelledby="heading{{ tg_bot.pk }}" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div class="container mt-4">
                <h2>Bot Settings</h2>
                <form id="update-bot-form">
                {% csrf_token %}

                    <div class="form-group" style="margin-top: 15px;">
                        <label for="id_bot_name{{ tg_bot.pk }}">Bot Name</label>
                        <input type="text" class="form-control bot-name" id="id_bot_name{{ tg_bot.pk }}" name="bot_name" value="{{ tg_bot.bot_name }}" required>
                    </div>

                    <div class="form-group" style="margin-top: 15px;">
                        <label for="id_api_key{{ tg_bot.pk }}">API Key</label>
                        <input type="text" class="form-control api-key" id="id_api_key{{ tg_bot.pk }}" name="api_key" value="{{ tg_bot.api_key }}" required>
                    </div>

                    <div class="form-group" style="margin: 10px 0px 10px 0px;">
                        <label for="id_webhook_url{{ tg_bot.pk }}">Webhook URL</label>
                        <input type="url" class="form-control webhook-url" id="id_webhook_url{{ tg_bot.pk }}" name="webhook_url" value="{{ tg_bot.webhook_url }}" required>
                    </div>

                    <div style="display:flex;">
                        <button type="button" class="btn btn-primary update-bot-button" data-url="{% url 'tg_bot_operation_by_id' pk=tg_bot.pk %}">Update</button>
                        <button type="button" class="btn btn-danger delete-tg-bot-btn delete-btn" data-url="{% url 'tg_bot_operation_by_id' pk=tg_bot.pk %}" style="margin-left:10px">Delete</button>
                    </div>
                </form>

                <form action="{% url 'set_webhook' %}" method="POST" style="margin:0px 0px 0px 0px;">
                    {% csrf_token %}
                    <input type="hidden" name="bot_id" value="{{ tg_bot.id }}">
                    <button type="submit" class="btn btn-success">Set/Remove Webhook</button>
                    {{ form.errors }}
                </form>
            </div>
          </div>
        </div>
    </div>
  {% endfor %}
</div>
{% endif %}
{% endblock %}

templates/create_store_item.html
{% extends 'base.html' %}
{% block title %}Create store item{% endblock %}
{% block h1 %}<h1 style="text-align: center; color:#dc3545; margin:50px;">Create product card</h1>{% endblock %}
{% block create-store-item %}
<form method="POST" action="{% url 'create_product_page' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <label for="id_name">Product Name</label>
        <input type="text" name="name" class="form-control" id="id_name">
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_price">Price</label>
        <input type="number" name="price" class="form-control" id="id_price">
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_description">Description</label>
        <textarea name="description" class="form-control" id="id_description"></textarea>
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_category">Category</label>
        <select class="form-select form-select-sm" id="id_category" aria-label=".form-select-sm" name="category">
            <option value="" disabled selected>Select category</option>
            <option value="1">Technics</option>
        </select>
    </div>

    <div class="form-group" style="display: flex; margin-top: 15px; flex-direction: column;">
        <label for="id_image">Product Image</label>
        <input type="file" name="image" class="form-control-file" id="id_image">
    </div>

    <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Create</button>

    {{ form.errors }}
</form>

{% endblock %}

templates/forbidden.html
{% extends 'base.html' %}
{% block title %}ERROR 403{% endblock %}
{% block h1 %}{% endblock %}
{% block forbidden %}
<div class="container py-5" style="margin-top: 120px;">
     <div class="row">
          <div class="col-md-2 text-center">
               <p><i class="fa fa-exclamation-triangle fa-5x" style="color:#dc3545;"></i><br/>Status Code: 403</p>
          </div>
          <div class="col-md-10">
               <h3>OPPSSS!!!! Sorry...</h3>
               <p>Sorry, your access is refused due to security reasons of our server and also our sensitive data.<br/>Please go back to the previous page to continue browsing.</p>
               <a class="btn btn-danger" href="javascript:history.back()">Go Back</a>
          </div>
     </div>
</div>
{% endblock %}

templates/store.html
{% extends 'base.html' %}
{% block title %}Store{% endblock %}
{% block h1 %}{% endblock %}
{% block store %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% if request.user.is_superuser %}
          <a href="{% url 'create_product_page' %}" class="btn btn-sm btn-outline-dark d-flex align-items-center justify-content-center">Add product</a>
        {% endif %}

        {% for product in store_product_list %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ product.image.url }}" alt="{{ product.name }}" width="100%" height="225">
              <div class="card-body">
                <p class="card-text">{{product.name}}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-body-secondary">{{product.price}}</small>
                  {% if request.user.is_superuser %}
                  <div class="btn-group">
                      <a href = "{% url 'update_product' pk=product.pk %}" type="button" class="btn btn-sm btn-outline-primary">Update</a>
                      <button type="button" class="btn btn-sm btn-outline-danger delete-btn" data-url="{% url 'delete_product' pk=product.pk %}">Delete</button>
                  </div>
                  {% endif %}

                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-success">Add to cart</button>
                    <button type="button" class="btn btn-sm btn-outline-danger">Like</button>
                  </div>

                </div>
              </div>
            </div>
          </div>
         {% endfor %}
      </div>
    </div>
  </div>

{% if store_product_list.paginator.num_pages > 1 %}
<nav aria-label="Search results pages" style="display: flex; justify-content: center;">
  <ul class="pagination">
      {% if store_product_list.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ store_product_list.previous_page_number }}">Previous</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}

      {% for i in store_product_list.paginator.page_range %}
        {% if i > store_product_list.number|add:-2 and i < store_product_list.number|add:2 %}
          {% if store_product_list.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if store_product_list.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ store_product_list.next_page_number }}">Next</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}

templates/tg_users.html
{% extends 'base.html' %}
{% block title %}Tg users{% endblock %}
{% block h1%} <h1 style="text-align:center; margin:20px;">Telegram users</h1> {% endblock %}
{% block users_list %}
<h2 style="text-align:center; margin:20px;">Create new user</h2>
<form action="{% url 'tg_users_list' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="userHandle" class="form-label">Username</label>
        <input type="text" class="form-control" id="userHandle" name="username">
    </div>

    <div class="mb-3">
        <label for="firstUserName" class="form-label">First name</label>
        <input type="text" class="form-control" id="firstUserName" name="first_name"  required>
    </div>

    <div class="mb-3">
        <label for="lastUserName" class="form-label">Last name</label>
        <input type="text" class="form-control" id="lastUserName" name="last_name" required>
    </div>

    <div class="mb-3">
        <label class="form-label">Language</label>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="lang" id="flexRadioDefault1" value="en" checked {% if form.lang.value == 'en' %} checked {% endif %}>
            <label class="form-check-label" for="flexRadioDefault1">
                English
            </label>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="radio" name="lang" id="flexRadioDefault2" value="uk" {% if form.lang.value == 'uk' %} checked {% endif %}>
            <label class="form-check-label" for="flexRadioDefault2">
                Ukrainian
            </label>
        </div>
    </div>

    <button type="submit" class="btn btn-primary" >Submit</button>
{{ form.errors }}
</form>

<h2 style="text-align:center; margin:20px;">Users list</h2>

<table class="table table-dark table-striped" style="margin-bottom: 80px;">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Handle</th>
            <th scope="col">Lang</th>
            <th scope="col">Deleting</th>
        </tr>
    </thead>

    {% if tg_users_list %}
    <tbody>
        {% for tg_user in tg_users_list %}
        <tr>
            <th scope="row">{{tg_user.telegram_id}}</th>
            <td>{{tg_user.first_name}}</td>
            <td>{{tg_user.last_name}}</td>
            <td>{{tg_user.username}}</td>
            <td>{{tg_user.lang}}</td>
            <td>
                <button type="button" class="btn btn-danger delete-user-btn" data-url="{% url 'tg_users_operations_by_id' pk=tg_user.pk %}">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    {% endif %}
</table>
{% endblock %}

templates/update_store_item.html
{% extends 'base.html' %}
{% block title %}Create score item{% endblock %}
{% block h1 %}<h1 style="text-align: center; color:#dc3545; margin:50px;">Update product card</h1>{% endblock %}
{% block create-store-item %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_name">Product Name</label>
        <input type="text" name="name" class="form-control product-name" id="id_name" value='{{ form.name.value}}'>
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_price">Price</label>
        <input type="number" name="price" class="form-control product-price" id="id_price" value="{{ form.price.value }}">
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_description">Description</label>
        <textarea name="description" class="form-control product-description" id="id_description">{{ form.description.value }}</textarea>
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_category">Category</label>
        <input type="text" name="category" class="form-control product-category" id="id_category" value="{{ form.category.value }}">
    </div>

    <div class="form-group" style="margin-top: 15px;">
        <label for="id_image">Current Image</label><br>
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="Product Image" width="150">
        {% else %}
            <p>No image available.</p>
        {% endif %}


        <label for="id_image">Upload New Image (optional)</label>
        <input type="file" name="image" class="form-control-file product-image" id="id_image">

    </div>

    <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Update</button>
</form>
{% endblock %}